// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX0piAPwVD5N1PRbwe75w3Ik2TZJdnQtE',
    appId: '1:1093946793581:web:bf74c76e5131671cc76964',
    messagingSenderId: '1093946793581',
    projectId: 'smash-up-89005',
    authDomain: 'smash-up-89005.firebaseapp.com',
    storageBucket: 'smash-up-89005.appspot.com',
    measurementId: 'G-9YVEQPJT94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvO9IeXE5MTU3O3PgXX9RWk63fMrpbJME',
    appId: '1:1093946793581:android:4664c298833d7aecc76964',
    messagingSenderId: '1093946793581',
    projectId: 'smash-up-89005',
    storageBucket: 'smash-up-89005.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUe9UOtJMp4uvD3dZa8SB5V-z1jgDuG3Q',
    appId: '1:1093946793581:ios:2f073b7ffe60d4eac76964',
    messagingSenderId: '1093946793581',
    projectId: 'smash-up-89005',
    storageBucket: 'smash-up-89005.appspot.com',
    iosClientId: '1093946793581-tqk9qug0vi6bk32ff7j19q4rbrbcu0di.apps.googleusercontent.com',
    iosBundleId: 'com.example.smashUp',
  );
}
